version: '3'

services:
    app:
      build: ../
      container_name: app
      expose:
        - "3001"
      environment:
        - NGINX_FPM_PORT=3001
        - DB_HOST=db
        - DB_DATABASE=laravel
        - DB_USERNAME=root
        - DB_PASSWORD=root
      entrypoint: dockerize -template ./.docker/config-app-container/laravel/.env:.env -wait tcp://db:3306 -timeout 20s ./.docker/config-app-container/bin/entrypoint.sh
      volumes:
        - .:/var/www
        - ./.docker/config-app-container/bin/lvartisan:/usr/local/bin/lvartisan
      networks:
        - app-network
      depends_on:
        - db
        - redis
    nginx:
      depends_on:
        - app
      build: .docker/nginx
      container_name: nginx
      environment:
        - NGINX_FPM_HOST=app
        - NGINX_FPM_PORT=3001
      entrypoint: dockerize -template /var/www/.docker/config-app-container/dockerize/nginx.conf:/etc/nginx/conf.d/nginx.conf /var/www/.docker/nginx/entrypoint.sh
      restart: always
      tty: true
      ports:
        - "8000:80"
      volumes:
        - .:/var/www
      networks:
        - app-network
    redis:
      image: redis:alpine
      container_name: redis
      ports:
        - "6379:6379"
      networks:
        - app-network
    db:
      image: mysql:5.7
      command: --innodb-use-native-aio=0
      container_name: db
      restart: always
      tty: true
      ports:
        - "3306:3306"
      environment:
        - MYSQL_DATABASE=laravel
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_USER=root
      networks:
        - app-network
      volumes:
        - ./.docker/dbdata:/var/lib/mysql
networks:
  app-network:
    driver: bridge
